web:
  build: .
  command: python3 app.py
  ports:
    - "5000:5000"
  volumes:
    - videos_data:/app/videos
  depends_on:
    - redis
  environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379

worker:
  build: .
  command: python3 worker.py
  volumes:
    - videos_data:/app/videos
  depends_on:
    - redis
    - web
  environment:
    - REDIS_HOST=redis
    - REDIS_PORT=6379
